import {
  PROGRAM_ID,
  UPGRADE_AUTHORITY,
  DEFAULT_CLUSTER,
  CLUSTER_URLS,
  PDA_SEEDS,
  TOKEN_PROGRAM_ID,
  ASSOCIATED_TOKEN_PROGRAM_ID,
  SYSTEM_PROGRAM_ID,
  DEFAULT_COMMITMENT,
  CONFIRMATION_SETTINGS,
  LAMPORTS_PER_SOL,
  ESCROW_ACCOUNT_SIZE,
} from './constants';

import {
  deriveEscrowPDAs,
  deriveEscrowAddress,
  deriveVaultAddress,
  deriveTokenVaultAddress,
  deriveAssociatedTokenAccount,
  validateEscrowAddress,
  validateVaultAddress,
  validateTokenVaultAddress,
  getPDASeedsInfo,
} from './pda';

import {
  EscrowSDKError,
  EscrowProgramError,
  ValidationError,
  PDAError,
  TransactionError,
  PROGRAM_ERROR_CODES,
  EscrowStatus as EscrowStatusConst,
  isEscrowStatus,
} from './types';

import {
  validatePublicKey,
  validateU64,
  validateAgreementHash,
  validateExpiration,
  validateInitializeEscrowParams,
  validateSellerTokenAccount,
  validateBuyerTokenAccount,
  solToLamports,
  lamportsToSol,
  u64ToNumber,
  formatPubkey,
  formatAmount,
  extractProgramErrorCode,
  getProgramErrorMessage,
  isProgramError,
  getEscrowStatusName,
  isEscrowTerminal,
  canApprove,
  canRelease,
  canCancel,
  generateAgreementHash,
  createAgreementHashFromTerms,
  createAgreementHashFromData,
  retryWithBackoff,
  getCurrentTimestamp,
  addSeconds,
  createExpiration,
  isExpired,
  getTimeRemaining,
} from './utils';

import {
  EscrowClient,
  createEscrowClient,
  createReadOnlyClient,
  createClientWithKeypair,
} from './client';

// Re-export all named exports
export {
  // Constants
  PROGRAM_ID,
  UPGRADE_AUTHORITY,
  DEFAULT_CLUSTER,
  CLUSTER_URLS,
  PDA_SEEDS,
  TOKEN_PROGRAM_ID,
  ASSOCIATED_TOKEN_PROGRAM_ID,
  SYSTEM_PROGRAM_ID,
  DEFAULT_COMMITMENT,
  CONFIRMATION_SETTINGS,
  LAMPORTS_PER_SOL,
  ESCROW_ACCOUNT_SIZE,
  
  // PDA Derivation
  deriveEscrowPDAs,
  deriveEscrowAddress,
  deriveVaultAddress,
  deriveTokenVaultAddress,
  deriveAssociatedTokenAccount,
  validateEscrowAddress,
  validateVaultAddress,
  validateTokenVaultAddress,
  getPDASeedsInfo,
  
  // Types
  EscrowSDKError,
  EscrowProgramError,
  ValidationError,
  PDAError,
  TransactionError,
  PROGRAM_ERROR_CODES,
  EscrowStatusConst,
  isEscrowStatus,
  
  // Utilities
  validatePublicKey,
  validateU64,
  validateAgreementHash,
  validateExpiration,
  validateInitializeEscrowParams,
  validateSellerTokenAccount,
  validateBuyerTokenAccount,
  solToLamports,
  lamportsToSol,
  u64ToNumber,
  formatPubkey,
  formatAmount,
  extractProgramErrorCode,
  getProgramErrorMessage,
  isProgramError,
  getEscrowStatusName,
  isEscrowTerminal,
  canApprove,
  canRelease,
  canCancel,
  generateAgreementHash,
  createAgreementHashFromTerms,
  createAgreementHashFromData,
  retryWithBackoff,
  getCurrentTimestamp,
  addSeconds,
  createExpiration,
  isExpired,
  getTimeRemaining,
  
  // Client
  EscrowClient,
  createEscrowClient,
  createReadOnlyClient,
  createClientWithKeypair,
};

/**
 * Default export with all SDK functionality
 */
export default {
  // Constants
  PROGRAM_ID,
  UPGRADE_AUTHORITY,
  DEFAULT_CLUSTER,
  CLUSTER_URLS,
  PDA_SEEDS,
  TOKEN_PROGRAM_ID,
  ASSOCIATED_TOKEN_PROGRAM_ID,
  SYSTEM_PROGRAM_ID,
  DEFAULT_COMMITMENT,
  CONFIRMATION_SETTINGS,
  LAMPORTS_PER_SOL,
  ESCROW_ACCOUNT_SIZE,
  
  // PDA Derivation
  deriveEscrowPDAs,
  deriveEscrowAddress,
  deriveVaultAddress,
  deriveTokenVaultAddress,
  deriveAssociatedTokenAccount,
  validateEscrowAddress,
  validateVaultAddress,
  validateTokenVaultAddress,
  getPDASeedsInfo,
  
  // Types
  EscrowSDKError,
  EscrowProgramError,
  ValidationError,
  PDAError,
  TransactionError,
  PROGRAM_ERROR_CODES,
  EscrowStatusConst,
  isEscrowStatus,
  
  // Utilities
  validatePublicKey,
  validateU64,
  validateAgreementHash,
  validateExpiration,
  validateInitializeEscrowParams,
  validateSellerTokenAccount,
  validateBuyerTokenAccount,
  solToLamports,
  lamportsToSol,
  u64ToNumber,
  formatPubkey,
  formatAmount,
  extractProgramErrorCode,
  getProgramErrorMessage,
  isProgramError,
  getEscrowStatusName,
  isEscrowTerminal,
  canApprove,
  canRelease,
  canCancel,
  generateAgreementHash,
  createAgreementHashFromTerms,
  createAgreementHashFromData,
  retryWithBackoff,
  getCurrentTimestamp,
  addSeconds,
  createExpiration,
  isExpired,
  getTimeRemaining,
  
  // Client
  EscrowClient,
  createEscrowClient,
  createReadOnlyClient,
  createClientWithKeypair,
} as const;